version: 2
updates:
- package-ecosystem: "cargo"
  directory: "/"
  schedule:
    interval: "daily"
  reviewers:
    - "Kernel-Dirichlet"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  reviewers:
    - "Kernel-Dirichlet"
