name: Lint
on: [ push, pull_request ]
permissions:
  contents: read
jobs:
  rust:
    name: Cargo clippy & fmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Setup Rust toolchain
      run: rustup show && rustup update
    - name: Install GUI dependencies
      run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev libx11-dev libxkbcommon-dev libfontconfig-dev libxext-dev libxft-dev libxinerama-dev libxcursor-dev libxrender-dev libxfixes-dev
    - name: cargo fmt
      run: cargo fmt -- --check
    - name: cargo clippy
      run: cargo clippy --workspace --all-features --tests -- -D warnings

  udeps:
    name: Unused dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install nightly and cargo-udeps
        run: |
          rustup update
          rustup toolchain install nightly
          sudo apt-get install -y wget
          wget https://github.com/est31/cargo-udeps/releases/download/v0.1.55/cargo-udeps-v0.1.55-x86_64-unknown-linux-musl.tar.gz
          tar -xzf cargo-udeps-v0.1.55-x86_64-unknown-linux-musl.tar.gz
          mv cargo-udeps-v0.1.55-x86_64-unknown-linux-musl/cargo-udeps ~/.cargo/bin
          cargo +nightly udeps

  audit:
    name: Cargo Audit
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            crates.io:443
            github.com:443
            index.crates.io:443
            static.crates.io:443

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Cargo Audit
        run: cargo install cargo-audit

      - name: Run Cargo Audit
        run: cargo audit
